Repository arpitghura/typing-test, pull requests merged in 2022-10, with the labels that each got.

#4 encoded userName to prevent from XSS
  index.js
Labels: hacktoberfest, hacktoberfest-accepted

#11 Centered the footer, added a gradient background for the footer. Changes made in index.css and index.html
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, assigned, changes-requested

#19 Revert "Now user won't be able to copy the quote and paste into the usetInput."
  index.js
  practice.css
Labels: hacktoberfest, hacktoberfest-accepted, assigned

#21 fix: add GitHub icon and link
  index.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted, assigned

#20 Contributors added
  contributors.md
Labels: hacktoberfest, hacktoberfest-accepted

#17 Final Readme.md file
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, assigned, changes-requested

#24 Update about.html
  about.html
Labels: hacktoberfest, hacktoberfest-accepted

#27 table fixed
  practice.css
Labels: hacktoberfest, hacktoberfest-accepted, assigned, changes-requested

#34 Add navbar and footer to practice page
  practice.css
  practice.html
Labels: hacktoberfest, hacktoberfest-accepted

#30 profile page created
  profile.css
  profile.html
  profile.js
Labels: hacktoberfest, hacktoberfest-accepted

#40 Onboarded Difficulty level
  index.js
  practice.html
  profile.html
  profile.js
Labels: hacktoberfest, hacktoberfest-accepted

#47 changed the practice.css
  practice.css
Labels: hacktoberfest, hacktoberfest-accepted, changes-requested

#38 some fixes and minor feature additions
  README.md
  index.html
  practice.css
  practice.html
  practice.js
Labels: hacktoberfest, hacktoberfest-accepted, changes-requested

#49 Updated screengrabs of website and readme.md
  README.md
  assets/Homepage.png
  assets/Report.png
  assets/practice.png
Labels: hacktoberfest, hacktoberfest-accepted

#48 Added average speed and time in history section.
  practice.css
  practice.html
  practice.js
  profile.html
  profile.js
Labels: hacktoberfest, hacktoberfest-accepted, changes-requested

#52 enhc: making navbrand-name a link to homepage
  about.html
  index.css
  index.html
  practice.css
  practice.html
  profile.html
Labels: hacktoberfest, hacktoberfest-accepted, changes-requested
