Repository arpitghura/typing-test, pull requests merged in 2023-02, with the labels that each got.

#90 fixed footer bug
  assets/css/index.css
  index.html
Labels: diversion2k23

#92 changed ui of about section
  about.html
  assets/css/about.css
Labels: changes-requested, diversion2k23

#106 added icons in the navbar
  about.html
  assets/css/index.css
  index.html
  practice.html
  profile.html
  testimonials.html
Labels: changes-requested, iwoc

#109 Documentation of Source Code
  about.html
  assets/css/index.css
  assets/css/practice.css
  assets/css/profile.css
  assets/css/testimonials.css
  assets/js/dark.js
  assets/js/index.js
  assets/js/practice.mjs
  assets/js/profile.js
  assets/js/sentence.mjs
  index.html
  practice.html
  profile.html
  testimonials.html
Labels: changes-requested, diversion2k23

#96 Change in Colors and width of scroll bar
  assets/css/index.css
Labels: diversion2k23

#121 Update the profile section #117 solve
  assets/css/profile.css
Labels: diversion2k23

#125 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: changes-requested

#128 REFACTORED CSS AND JS
  assets/css/index.css
  assets/css/practice.css
  assets/css/profile.css
  assets/css/testimonials.css
  assets/js/dark.js
Labels: Medium, iwoc
